Add numerous methods to support IPDA use cases
NASA-PDS/updart pull request #36
Opened 2024-09-17 13:17 UTC by jordanpadams

## 🗒️ Summary
Add the following methods:
* `has_processing_level`
* `has_instrument`
* `bundles`
* `collections`
* `observationals`
* `has_investigation`

## ⚙️ Test Data and/or Report
Yeah... I tested it locally? But we probably need to figure out a good way to develop integration tests for this.

## ♻️ Related Issues

resolves #29
resolves #30
resolves #31
resolves #32
resolves #33
resolves #34
resolves #35

2024-09-17 15:13 UTC, nutjob4life approved these changes
Assuming `__add_clause` works, this looks fine 👍

2024-09-18 07:41 UTC, jordanpadams commented
@tloubrieu-jpl would you mind taking a look when you have a chance? you have a vision for the architecture here, so I want to make sure this is inline with what you were thinking.

2024-10-03 03:34 UTC, tloubrieu-jpl commented
@jordanpadams sorry I missed to look at it earlier. I will try to review it update when I have chance. This looks good but I have a couple of things I would like to look at:
- get: there might be a more efficient way to implement the query, not using the q parameters
- a few inline help are copy paste and need updates

2024-10-03 03:36 UTC, tloubrieu-jpl commented
I also would like to have test for each implemented method.

2024-10-07 17:47 UTC, jordanpadams commented
Mistakenly closed without merging

2024-10-17 16:33 UTC, tloubrieu-jpl requested changes

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def get(self, id: str):
inline help is a copy/paste, need to be revised

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def has_processing_level(self, processing_level: PROCESSING_LEVELS = "raw"):
test need to be added

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def has_instrument_host(self, id: str):
test need to be added

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def bundles(self):
test need to be added

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def collections(self, type: Optional[str] = None):
test need to be added

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def has_investigation(self, identifier: str):
test need to be added

2024-10-17 16:33 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +    def filter(self, clause: str):
test need to be added.

docstring copy/paste need to be updated

2024-10-30 20:25 UTC, tloubrieu-jpl approved these changes
That looks good, thanks @collinss-jpl .
I have minor comments that I shared here while I was going through the PR, but it is approved.

2024-10-30 20:25 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +        """Selects Collection products for a specific filter.
Not a critical feedback; I don't understand what the meaning of "for a specific filter" in this context.
I would say "Selects products of class Collection only" or "Select Collections only".

2024-10-30 20:25 UTC, tloubrieu-jpl commented on src/pds/updart/client.py
> +        """Selects Bundle products for a specific filter.
Same as above

2024-10-30 21:30 UTC, merged